// <auto-generated />
using System;
using MBOKA_IMMO.src.MbokaImmo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MBOKA_IMMO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323102825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("IdAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAgent"));

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("NbVisites")
                        .HasColumnType("integer");

                    b.Property<string>("ZoneIntervention")
                        .HasColumnType("text");

                    b.HasKey("IdAgent");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Artisan", b =>
                {
                    b.Property<int>("IdArtisan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArtisan"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("NbInterventions")
                        .HasColumnType("integer");

                    b.Property<float>("NoteMoyenne")
                        .HasColumnType("real");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TarifHoraire")
                        .HasColumnType("numeric");

                    b.Property<string>("ZoneIntervention")
                        .HasColumnType("text");

                    b.HasKey("IdArtisan");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Artisans");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", b =>
                {
                    b.Property<int>("IdBien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBien"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CautionMois")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Disponibilite")
                        .HasColumnType("date");

                    b.Property<int>("IdProprietaire")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoyerMensuel")
                        .HasColumnType("numeric");

                    b.Property<int>("Pieces")
                        .HasColumnType("integer");

                    b.Property<string>("Quartier")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Valide")
                        .HasColumnType("boolean");

                    b.Property<string>("Video")
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBien");

                    b.HasIndex("IdProprietaire");

                    b.ToTable("Biens");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Candidature", b =>
                {
                    b.Property<int>("IdCandidature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCandidature"));

                    b.Property<DateTime>("DateCandidature")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBien")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocataire")
                        .HasColumnType("integer");

                    b.Property<string>("JustificatifUrl")
                        .HasColumnType("text");

                    b.Property<string>("MessageMotivation")
                        .HasColumnType("text");

                    b.Property<string>("PieceIdentiteUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("RevenusMenuels")
                        .HasColumnType("numeric");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCandidature");

                    b.HasIndex("IdBien");

                    b.HasIndex("IdLocataire");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("IdConversation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConversation"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DernierMessage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Participant1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Participant2Id")
                        .HasColumnType("integer");

                    b.HasKey("IdConversation");

                    b.HasIndex("Participant1Id");

                    b.HasIndex("Participant2Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Favori", b =>
                {
                    b.Property<int>("IdFavori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFavori"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBien")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.HasKey("IdFavori");

                    b.HasIndex("IdBien");

                    b.HasIndex("IdUser");

                    b.ToTable("Favoris");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Intervention", b =>
                {
                    b.Property<int>("IdIntervention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIntervention"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateIntervention")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSignalement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DevisMontant")
                        .HasColumnType("numeric");

                    b.Property<bool>("DevisValide")
                        .HasColumnType("boolean");

                    b.Property<string>("FactureUrl")
                        .HasColumnType("text");

                    b.Property<int?>("IdArtisan")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("NoteLocataire")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urgence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdIntervention");

                    b.HasIndex("IdArtisan");

                    b.HasIndex("IdLocation");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", b =>
                {
                    b.Property<int>("IdLocataire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocataire"));

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreCreditworthiness")
                        .HasColumnType("integer");

                    b.HasKey("IdLocataire");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Locataires");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Location", b =>
                {
                    b.Property<int>("IdLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocation"));

                    b.Property<string>("BailUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Caution")
                        .HasColumnType("numeric");

                    b.Property<bool>("CautionPayee")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateSignature")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBien")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocataire")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoyerMensuel")
                        .HasColumnType("numeric");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLocation");

                    b.HasIndex("IdBien");

                    b.HasIndex("IdLocataire");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer");

                    b.Property<int>("IdConversation")
                        .HasColumnType("integer");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean");

                    b.Property<string>("PieceJointe")
                        .HasColumnType("text");

                    b.HasKey("IdMessage");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("IdConversation");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Lien")
                        .HasColumnType("text");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdUser");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaiement"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLocation")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MontantNet")
                        .HasColumnType("numeric");

                    b.Property<string>("Operateur")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdLocation");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.PaiementIntervention", b =>
                {
                    b.Property<int>("IdPaiementInterv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaiementInterv"));

                    b.Property<int>("IdArtisan")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaiement")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantArtisan")
                        .HasColumnType("numeric");

                    b.HasKey("IdPaiementInterv");

                    b.HasIndex("IdArtisan");

                    b.HasIndex("IdPaiement")
                        .IsUnique();

                    b.ToTable("PaiementsIntervention");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.PaiementLoyer", b =>
                {
                    b.Property<int>("IdPaiementLoyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaiementLoyer"));

                    b.Property<int>("IdPaiement")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("MoisConcerne")
                        .HasColumnType("date");

                    b.HasKey("IdPaiementLoyer");

                    b.HasIndex("IdPaiement")
                        .IsUnique();

                    b.ToTable("PaiementsLoyer");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("IdPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhoto"));

                    b.Property<int?>("BienIdBien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntiteId")
                        .HasColumnType("integer");

                    b.Property<string>("EntiteType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InterventionIdIntervention")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VisiteIdVisite")
                        .HasColumnType("integer");

                    b.HasKey("IdPhoto");

                    b.HasIndex("BienIdBien");

                    b.HasIndex("InterventionIdIntervention");

                    b.HasIndex("VisiteIdVisite");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Proprietaire", b =>
                {
                    b.Property<int>("IdProprio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProprio"));

                    b.Property<string>("CompteBancaire")
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .HasColumnType("text");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.HasKey("IdProprio");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Proprietaires");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<bool>("CompteActif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KycValide")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaysResidence")
                        .HasColumnType("text");

                    b.Property<string>("PieceIdentite")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("VilleResidence")
                        .HasColumnType("text");

                    b.HasKey("IdUser");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Virement", b =>
                {
                    b.Property<int>("IdVirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVirement"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DateVirement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IbanDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProprio")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantNet")
                        .HasColumnType("numeric");

                    b.Property<string>("Operateur")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceBanque")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVirement");

                    b.HasIndex("IdProprio");

                    b.ToTable("Virements");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Visite", b =>
                {
                    b.Property<int>("IdVisite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVisite"));

                    b.Property<string>("CompteRendu")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateVisite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAgent")
                        .HasColumnType("integer");

                    b.Property<int>("IdBien")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocataire")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVisite");

                    b.HasIndex("IdAgent");

                    b.HasIndex("IdBien");

                    b.HasIndex("IdLocataire");

                    b.ToTable("Visites");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Agent", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Agent")
                        .HasForeignKey("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Agent", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Artisan", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Artisan")
                        .HasForeignKey("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Artisan", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Proprietaire", "Proprietaire")
                        .WithMany("Biens")
                        .HasForeignKey("IdProprietaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Candidature", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", "Bien")
                        .WithMany("Candidatures")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", "Locataire")
                        .WithMany("Candidatures")
                        .HasForeignKey("IdLocataire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Participant1")
                        .WithMany("Conversations1")
                        .HasForeignKey("Participant1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Participant2")
                        .WithMany("Conversations2")
                        .HasForeignKey("Participant2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant1");

                    b.Navigation("Participant2");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Favori", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", "Bien")
                        .WithMany("Favoris")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Favoris")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Artisan", "Artisan")
                        .WithMany("Interventions")
                        .HasForeignKey("IdArtisan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Location", "Location")
                        .WithMany("Interventions")
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artisan");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Locataire")
                        .HasForeignKey("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Location", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", "Bien")
                        .WithMany("Locations")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", "Locataire")
                        .WithMany("Locations")
                        .HasForeignKey("IdLocataire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Message", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Expediteur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Location", "Location")
                        .WithMany("Paiements")
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.PaiementIntervention", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Artisan", "Artisan")
                        .WithMany("PaiementsIntervention")
                        .HasForeignKey("IdArtisan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Paiement", "Paiement")
                        .WithOne("PaiementIntervention")
                        .HasForeignKey("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.PaiementIntervention", "IdPaiement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artisan");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.PaiementLoyer", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Paiement", "Paiement")
                        .WithOne("PaiementLoyer")
                        .HasForeignKey("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.PaiementLoyer", "IdPaiement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Photo", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", null)
                        .WithMany("Photos")
                        .HasForeignKey("BienIdBien");

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Intervention", null)
                        .WithMany("Photos")
                        .HasForeignKey("InterventionIdIntervention");

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Visite", null)
                        .WithMany("Photos")
                        .HasForeignKey("VisiteIdVisite");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Proprietaire", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Proprietaire")
                        .HasForeignKey("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Proprietaire", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Virement", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Proprietaire", "Proprietaire")
                        .WithMany("Virements")
                        .HasForeignKey("IdProprio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Visite", b =>
                {
                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Agent", "Agent")
                        .WithMany("Visites")
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", "Bien")
                        .WithMany("Visites")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", "Locataire")
                        .WithMany("Visites")
                        .HasForeignKey("IdLocataire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Bien");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Visites");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Artisan", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("PaiementsIntervention");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Bien", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Favoris");

                    b.Navigation("Locations");

                    b.Navigation("Photos");

                    b.Navigation("Visites");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Intervention", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Locataire", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Locations");

                    b.Navigation("Visites");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Location", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Paiement", b =>
                {
                    b.Navigation("PaiementIntervention");

                    b.Navigation("PaiementLoyer");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Proprietaire", b =>
                {
                    b.Navigation("Biens");

                    b.Navigation("Virements");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("Artisan");

                    b.Navigation("Conversations1");

                    b.Navigation("Conversations2");

                    b.Navigation("Favoris");

                    b.Navigation("Locataire");

                    b.Navigation("MessagesEnvoyes");

                    b.Navigation("Notifications");

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("MBOKA_IMMO.src.MbokaImmo.Domain.Entities.Visite", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
